site_name: Barcamp3
site_url: https://oerbase.github.io/Barcamp3/
theme:
  name: material
  font: 
    text: Fira Code
  palette:
    primary: black
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - assets/css/reset.css
  - assets/css/global.css
  - assets/css/tweaks.css
  - assets/css/landing-page-layout.css
  - assets/css/landing-page-sections.css
  - assets/css/tooltips.css
  - assets/css/calendar.css

plugins:
  - privacy
