site_name: Barcamp3
site_url: https://oerbase.github.io/Barcamp3/
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - assets/css/reset.css
  - assets/css/tooltips.css
  - assets/css/tweaks.css

plugins:
  - privacy
